# Generated by Django 5.0.4 on 2024-05-06 12:23

import dbapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(default=dbapp.models.ReferenceID.generate_reference_id, editable=False, max_length=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('surname', models.CharField(max_length=100)),
                ('other_names', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('home_address', models.TextField()),
                ('house_fellowship_zone', models.CharField(max_length=100)),
                ('next_of_kin', models.CharField(max_length=100)),
                ('next_of_kin_phone_number', models.CharField(max_length=15)),
                ('home_town', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('lga', models.CharField(max_length=100, verbose_name='Local Government Area')),
                ('nationality', models.CharField(max_length=100)),
                ('tribe', models.CharField(max_length=100)),
                ('other_languages', models.CharField(max_length=100)),
                ('close_townmate', models.CharField(max_length=100, verbose_name='Close Townmate')),
                ('townmate_phone_number', models.CharField(max_length=15, verbose_name="Townmate's Phone Number")),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('W', 'Widow or Widower')], max_length=1)),
                ('other_information', models.CharField(blank=True, max_length=100, null=True)),
                ('blood_group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2)),
                ('rhesus', models.CharField(choices=[('+', 'Positive'), ('-', 'Negative')], max_length=1)),
                ('profession_sector', models.CharField(choices=[('CS', 'Civil Servant'), ('PS', 'Public Servant'), ('PRI', 'Private Sector'), ('ART', 'Artisan'), ('RET', 'Retired'), ('STU', 'STUDENT')], max_length=3)),
                ('employed', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('profession', models.CharField(blank=True, max_length=150, null=True)),
                ('place_of_work', models.CharField(blank=True, max_length=100, null=True)),
                ('position_at_work', models.CharField(blank=True, max_length=100, null=True)),
                ('w_year', models.DateField(blank=True, null=True)),
                ('student', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=3, null=True)),
                ('field_of_study', models.CharField(blank=True, max_length=100, null=True, verbose_name='Field or Course of Study')),
                ('school', models.CharField(blank=True, max_length=150, null=True)),
                ('position_in_school', models.CharField(blank=True, max_length=100, null=True)),
                ('s_year', models.DateField(blank=True, null=True)),
                ('baptised', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3)),
                ('by_immersion', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3)),
                ('denomination', models.CharField(max_length=150)),
                ('church_worker', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3)),
                ('units', models.CharField(max_length=200)),
                ('church_group', models.CharField(max_length=150)),
                ('fellowship_group', models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('Y', 'Youth')], max_length=5)),
                ('other_relevant_information', models.TextField(blank=True, null=True)),
                ('name_of_member_closest_to_you', models.CharField(max_length=150)),
                ('when_did_you_become_a_member_of_the_church', models.CharField(max_length=20)),
                ('church_status', models.CharField(choices=[('A', 'Active'), ('D', 'Diaspora')], max_length=10)),
                ('leadership_position_held1', models.CharField(blank=True, max_length=50, null=True)),
                ('year1', models.DateField(blank=True, null=True)),
                ('leadership_position_held2', models.CharField(blank=True, max_length=50, null=True)),
                ('year2', models.DateField(blank=True, null=True)),
                ('leadership_position_held3', models.CharField(blank=True, max_length=50, null=True)),
                ('year3', models.DateField(blank=True, null=True)),
                ('leadership_position_held4', models.CharField(blank=True, max_length=50, null=True)),
                ('year4', models.DateField(blank=True, null=True)),
                ('leadership_position_held5', models.CharField(blank=True, max_length=50, null=True)),
                ('year5', models.DateField(blank=True, null=True)),
                ('current_class', models.CharField(blank=True, max_length=150, null=True)),
                ('current_class_year', models.DateField(blank=True, null=True)),
                ('current_school', models.CharField(blank=True, max_length=150, null=True)),
                ('current_school_year', models.DateField(blank=True, null=True)),
                ('comment_on_member', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
